#!/usr/bin/env bash
#
# AppScope Agent Installation Script
# Usage: curl -sSL https://appscope.io/install.sh | bash -s -- --key YOUR_API_KEY
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
BINARY_NAME="appscope"
VERSION="1.0.0"
GITHUB_REPO="appscope/agent"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/appscope"
LOG_DIR="/var/log/appscope"
LIB_DIR="/var/lib/appscope"
SERVICE_NAME="appscope"

# Parse command line arguments
API_KEY=""
SKIP_SERVICE=false
FORCE=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --key)
            API_KEY="$2"
            shift 2
            ;;
        --skip-service)
            SKIP_SERVICE=true
            shift
            ;;
        --force)
            FORCE=true
            shift
            ;;
        --help)
            echo "AppScope Agent Installation Script"
            echo ""
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --key KEY           API key for AppScope (required)"
            echo "  --skip-service      Skip systemd/launchd service installation"
            echo "  --force             Force reinstallation"
            echo "  --help              Display this help message"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Functions
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        print_error "This script must be run as root or with sudo"
        exit 1
    fi
}

# Detect OS and architecture
detect_platform() {
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    ARCH=$(uname -m)

    case $OS in
        linux)
            OS="linux"
            ;;
        darwin)
            OS="darwin"
            ;;
        *)
            print_error "Unsupported operating system: $OS"
            exit 1
            ;;
    esac

    case $ARCH in
        x86_64|amd64)
            ARCH="amd64"
            ;;
        aarch64|arm64)
            ARCH="arm64"
            ;;
        *)
            print_error "Unsupported architecture: $ARCH"
            exit 1
            ;;
    esac

    PLATFORM="${OS}-${ARCH}"
    print_info "Detected platform: $PLATFORM"
}

# Download binary
download_binary() {
    print_info "Downloading AppScope Agent v${VERSION} for ${PLATFORM}..."

    DOWNLOAD_URL="https://github.com/${GITHUB_REPO}/releases/download/v${VERSION}/${BINARY_NAME}-${PLATFORM}"
    TEMP_FILE="/tmp/${BINARY_NAME}-${PLATFORM}"

    if command -v curl > /dev/null 2>&1; then
        curl -fsSL -o "$TEMP_FILE" "$DOWNLOAD_URL"
    elif command -v wget > /dev/null 2>&1; then
        wget -q -O "$TEMP_FILE" "$DOWNLOAD_URL"
    else
        print_error "Neither curl nor wget found. Please install one of them."
        exit 1
    fi

    if [[ ! -f "$TEMP_FILE" ]]; then
        print_error "Failed to download binary"
        exit 1
    fi

    print_success "Binary downloaded successfully"
}

# Install binary
install_binary() {
    print_info "Installing binary to $INSTALL_DIR..."

    chmod +x "$TEMP_FILE"
    mv "$TEMP_FILE" "${INSTALL_DIR}/${BINARY_NAME}"

    print_success "Binary installed to ${INSTALL_DIR}/${BINARY_NAME}"
}

# Create directories
create_directories() {
    print_info "Creating directories..."

    mkdir -p "$CONFIG_DIR"
    mkdir -p "$LOG_DIR"
    mkdir -p "$LIB_DIR"

    print_success "Directories created"
}

# Create configuration file
create_config() {
    CONFIG_FILE="${CONFIG_DIR}/config.yaml"

    if [[ -f "$CONFIG_FILE" ]] && [[ "$FORCE" != true ]]; then
        print_warning "Configuration file already exists at $CONFIG_FILE"
        print_info "Skipping configuration creation (use --force to overwrite)"
        return
    fi

    print_info "Creating configuration file..."

    cat > "$CONFIG_FILE" << EOF
# AppScope Agent Configuration
# Generated by install script

# Your AppScope API key (required)
api_key: "${API_KEY}"

# Project name - change this to your application name
project: "my-application"

# AppScope server URL
server_url: "https://api.appscope.io"

# Log files to monitor (add your application logs here)
logs:
  # - /var/log/myapp/application.log
  # - /var/log/nginx/access.log
  # - /var/log/nginx/error.log

# Database configuration (optional)
# database:
#   type: postgres
#   host: localhost
#   port: 5432
#   user: monitor_readonly
#   password: "\${DB_PASSWORD}"
#   dbname: myapp
#   metrics_only: true

# System metrics collection
system_metrics: true

# Collection interval in seconds
collection_interval: 30

# Health endpoint port
health_port: 9090
EOF

    chmod 600 "$CONFIG_FILE"
    print_success "Configuration created at $CONFIG_FILE"
}

# Install systemd service (Linux)
install_systemd_service() {
    print_info "Installing systemd service..."

    cat > "/etc/systemd/system/${SERVICE_NAME}.service" << EOF
[Unit]
Description=AppScope Agent
Documentation=https://docs.appscope.io
After=network.target

[Service]
Type=simple
User=root
ExecStart=${INSTALL_DIR}/${BINARY_NAME} --config ${CONFIG_DIR}/config.yaml
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${LOG_DIR} ${LIB_DIR}

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable "${SERVICE_NAME}.service"

    print_success "Systemd service installed"
}

# Install launchd service (macOS)
install_launchd_service() {
    print_info "Installing launchd service..."

    cat > "/Library/LaunchDaemons/com.appscope.agent.plist" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.appscope.agent</string>
    <key>ProgramArguments</key>
    <array>
        <string>${INSTALL_DIR}/${BINARY_NAME}</string>
        <string>--config</string>
        <string>${CONFIG_DIR}/config.yaml</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${LOG_DIR}/agent.log</string>
    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/agent.log</string>
</dict>
</plist>
EOF

    chmod 644 "/Library/LaunchDaemons/com.appscope.agent.plist"
    launchctl load "/Library/LaunchDaemons/com.appscope.agent.plist"

    print_success "Launchd service installed"
}

# Install service
install_service() {
    if [[ "$SKIP_SERVICE" == true ]]; then
        print_info "Skipping service installation (--skip-service flag)"
        return
    fi

    case $OS in
        linux)
            if command -v systemctl > /dev/null 2>&1; then
                install_systemd_service
            else
                print_warning "systemd not found, skipping service installation"
            fi
            ;;
        darwin)
            if command -v launchctl > /dev/null 2>&1; then
                install_launchd_service
            else
                print_warning "launchd not found, skipping service installation"
            fi
            ;;
    esac
}

# Verify installation
verify_installation() {
    print_info "Verifying installation..."

    if ! command -v "$BINARY_NAME" > /dev/null 2>&1; then
        print_error "Binary not found in PATH"
        exit 1
    fi

    VERSION_OUTPUT=$("$BINARY_NAME" --version 2>&1 || echo "")
    if [[ -z "$VERSION_OUTPUT" ]]; then
        print_warning "Could not verify binary version"
    else
        print_success "Binary version: $VERSION_OUTPUT"
    fi
}

# Print next steps
print_next_steps() {
    echo ""
    echo -e "${GREEN}============================================${NC}"
    echo -e "${GREEN}AppScope Agent Installation Complete!${NC}"
    echo -e "${GREEN}============================================${NC}"
    echo ""
    echo "Next steps:"
    echo ""
    echo "1. Edit configuration file:"
    echo -e "   ${BLUE}sudo nano ${CONFIG_DIR}/config.yaml${NC}"
    echo ""
    echo "2. Update the following settings:"
    echo "   - api_key: Your AppScope API key"
    echo "   - project: Your application name"
    echo "   - logs: Paths to your application log files"
    echo ""

    if [[ "$SKIP_SERVICE" != true ]]; then
        case $OS in
            linux)
                echo "3. Start the agent:"
                echo -e "   ${BLUE}sudo systemctl start ${SERVICE_NAME}${NC}"
                echo ""
                echo "4. Check agent status:"
                echo -e "   ${BLUE}sudo systemctl status ${SERVICE_NAME}${NC}"
                echo ""
                echo "5. View logs:"
                echo -e "   ${BLUE}sudo journalctl -u ${SERVICE_NAME} -f${NC}"
                ;;
            darwin)
                echo "3. Agent is already running (started by launchd)"
                echo ""
                echo "4. Check agent status:"
                echo -e "   ${BLUE}launchctl list | grep appscope${NC}"
                echo ""
                echo "5. View logs:"
                echo -e "   ${BLUE}tail -f ${LOG_DIR}/agent.log${NC}"
                ;;
        esac
    else
        echo "3. Run the agent manually:"
        echo -e "   ${BLUE}sudo ${BINARY_NAME} --config ${CONFIG_DIR}/config.yaml${NC}"
    fi

    echo ""
    echo "Health check endpoint:"
    echo -e "   ${BLUE}curl http://localhost:9090/health${NC}"
    echo ""
    echo "Documentation: https://docs.appscope.io"
    echo "Support: support@appscope.io"
    echo ""
}

# Main installation process
main() {
    echo ""
    echo "========================================"
    echo "AppScope Agent Installation Script"
    echo "Version: $VERSION"
    echo "========================================"
    echo ""

    # Validate API key
    if [[ -z "$API_KEY" ]]; then
        print_error "API key is required. Use --key YOUR_API_KEY"
        exit 1
    fi

    if [[ ! "$API_KEY" =~ ^ask_ ]]; then
        print_error "Invalid API key format. API key must start with 'ask_'"
        exit 1
    fi

    check_root
    detect_platform
    download_binary
    install_binary
    create_directories
    create_config
    install_service
    verify_installation
    print_next_steps
}

# Run main
main
